### ISSUE TITLE
Range script for ArcGIS Data

### ISSUE THREAD

**Issue by mikehern** [CaravanStudios/range#35]
- [x] Store latest [count](https://services1.arcgis.com/RLQu0rK7h4kbsBq5/ArcGIS/rest/services/Summer_Meal_Sites_2020/FeatureServer/0/query?where=OBJECTID+%3E%3D+0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=true&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=OBJECTID&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=)

- [x] Filter `features` and save [data](https://services1.arcgis.com/RLQu0rK7h4kbsBq5/ArcGIS/rest/services/Summer_Meal_Sites_2020/FeatureServer/0/query?where=OBJECTID+%3E%3D+0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=OBJECTID&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=1000&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=) to a folder
- [x] Stitch all JSON files to a single file
- [x] Convert JSON to CSV
- [x] Test CSV against `foodImport` script

**Comment by caravansteve** [comment]
Hi @mikehern -- can we make sure this script gets put in a Github repo if it isn't already?

**Comment by caravansteve** [comment]
Hey @mikehern! Just closing out some issues -- this was from the May sprint which was released, but I noticed there are still some unchecked items in the checklist. Is this work complete? If so, I'll go ahead and close it. If not, how about we separate out any remaining items into a separate ticket and put it on the current release board?
Thanks!

**Comment by mikehern** [comment]
Yes this can be considered "done", and ready to be closed.  Including a referencing link for tracking:

https://github.com/CaravanStudios/range-datascripts

**Comment by caravansteve** [comment]
Thanks Mike!
